# Generated by Django 5.2 on 2025-10-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='номер изображения'),
        ),
    ]
