# Generated by Django 5.2 on 2025-10-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
    ]
